### PR TITLE
feat: save write ack event height

### PR DESCRIPTION
**Pull request by viveksharmapoudel**
## Description

Saving write ack height needed for generating write ack packet.

### Commit Message

```bash
feat: save write ack event height
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)
- [ ] I have added version bump label on PR.

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by ibrizsabin — DISMISSED** [review]

**Review by AntonAndell — CHANGES_REQUESTED** [review]
Looks like formatting or indentation has changed making the diff way larger than it should be, make sure the indentation is correct and only commit relevnat changes

**Review by AntonAndell — CHANGES_REQUESTED** [review]
It has no tests to test the new method, which would be easy to add. To double check that is behaves as expected

**Review by AntonAndell — APPROVED** [review]
LGTM, dont forget to check the boxes of your PR

**Review by redlarva — APPROVED** [review]
looks good

**Comment by redlarva** [comment]
duplicate #734

**Pull request closed without merging**
