### PR TITLE
ci: add release workflow

### PR DESCRIPTION
**Pull request by DeepakBomjan**
* ci: use PAT

* ci: fix release assets upload issue

* ci: rename wasm file with version on filename

* ci: add changelog in release

### Commit Message

```bash
type: commit message
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by ibrizsabin** [comment]
@DeepakBomjan  i think we would also need to do a version bump. For rust contracts bumping version on workspace cargo.toml should be enough.

**Comment by DeepakBomjan** [comment]
Issue covered:
#563

**Comment by DeepakBomjan** [comment]
> @DeepakBomjan i think we would also need to do a version bump. For rust contracts bumping version on workspace cargo.toml should be enough.

Automatic version bump will be covered on #627

**Review by redlarva — APPROVED** [review]
looks good to me

**Pull request merged**
